// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { supabase } from './client'

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;
const LOCAL_SESSION_STORAGE_KEY = "mobi-connect-local-session";
const LOCAL_SESSION_HEADER = "x-local-session";

function encodeSessionForHeader(value: string) {
  if (typeof btoa !== "undefined") {
    return btoa(value);
  }
  return Buffer.from(value, "utf8").toString("base64");
}

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    const headers: Record<string, string> = {};

    if (SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY) {
      try {
        const { data } = await supabase.auth.getSession();
        const token = data.session?.access_token;
        if (token) {
          return next({ headers: { Authorization: `Bearer ${token}` } });
        }
      } catch {
        // fall back to local session header if supabase auth is unavailable
      }
    }

    if (typeof window !== "undefined") {
      const localSession = window.localStorage.getItem(LOCAL_SESSION_STORAGE_KEY);
      if (localSession) {
        headers[LOCAL_SESSION_HEADER] = encodeSessionForHeader(localSession);
      }
    }

    return next({ headers });
  },
)
