// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { existsSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function loadDotEnvIfNeeded() {
  const envPath = resolve(process.cwd(), '.env');
  if (!existsSync(envPath)) return;

  const envText = readFileSync(envPath, 'utf8');
  for (const rawLine of envText.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;
    const match = line.match(/^([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$/);
    if (!match) continue;
    const key = match[1];
    let value = match[2] ?? '';
    if (value.startsWith('"') && value.endsWith('"')) {
      value = value.slice(1, -1);
    } else if (value.startsWith("'") && value.endsWith("'")) {
      value = value.slice(1, -1);
    }
    if (process.env[key] === undefined) {
      process.env[key] = value;
    }
  }
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function getProjectRefFromUrl(url: string): string | undefined {
  try {
    const host = new URL(url).hostname;
    return host.replace(/\.supabase\.co$/i, '').replace(/\.supabase\.in$/i, '');
  } catch {
    return undefined;
  }
}

function getKeyProjectRef(key: string): string | undefined {
  if (!key.startsWith('eyJ')) return undefined;
  try {
    const payload = key.split('.')[1];
    const normalized = payload.replace(/-/g, '+').replace(/_/g, '/');
    const padded = normalized.padEnd(normalized.length + ((4 - (normalized.length % 4)) % 4), '=');
    const decoded = Buffer.from(padded, 'base64').toString('utf8');
    const parsed = JSON.parse(decoded) as { ref?: string };
    return parsed.ref;
  } catch {
    return undefined;
  }
}

function createSupabaseAdminClient() {
  loadDotEnvIfNeeded();
  const viteEnv = (import.meta as ImportMeta & { env?: Record<string, string | undefined> }).env;
  const SUPABASE_URL = process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL || viteEnv?.VITE_SUPABASE_URL;
  const SUPABASE_SERVICE_ROLE_KEY = [
    process.env.SUPABASE_SERVICE_ROLE_KEY,
    process.env.SUPABASE_SERVICE_ROLE_SECRET,
    process.env.SUPABASE_SECRET_KEY,
    process.env.VITE_SUPABASE_SERVICE_ROLE_KEY,
  ].find((value): value is string => Boolean(value && value.trim()));

  if (!SUPABASE_URL) {
    const message = 'Missing Supabase environment variable(s): SUPABASE_URL. Connect Supabase in Lovable Cloud.';
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  if (!SUPABASE_SERVICE_ROLE_KEY) {
    const message = 'SUPABASE_SERVICE_ROLE_KEY is not configured. Create a .env with SUPABASE_SERVICE_ROLE_KEY or set it in the shell.';
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  if (SUPABASE_SERVICE_ROLE_KEY.startsWith('sb_publishable_')) {
    const message = 'A publishable Supabase key was provided for admin access. Set SUPABASE_SERVICE_ROLE_KEY to the service-role secret.';
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  const keyProjectRef = getKeyProjectRef(SUPABASE_SERVICE_ROLE_KEY);
  const urlProjectRef = getProjectRefFromUrl(SUPABASE_URL);
  if (keyProjectRef && urlProjectRef && keyProjectRef !== urlProjectRef) {
    const message = `Supabase key project mismatch: key belongs to ${keyProjectRef} but URL points to ${urlProjectRef}. Use the matching service-role key for this project.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  const keyToUse = SUPABASE_SERVICE_ROLE_KEY;

  return createClient<Database>(SUPABASE_URL, keyToUse, {
    global: {
      fetch: createSupabaseFetch(keyToUse),
    },
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    }
  });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Load inside server handlers: const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
// Top-level import is safe only in other .server.ts modules - route files and *.functions.ts ship to the client bundle.
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
